// Candid Type Opcodes (SLEB128 encoded negative integers)

///|
pub const TYPE_NULL : Int64 = -1

///|
pub const TYPE_BOOL : Int64 = -2

///|
pub const TYPE_NAT : Int64 = -3

///|
pub const TYPE_INT : Int64 = -4

///|
pub const TYPE_NAT8 : Int64 = -5

///|
pub const TYPE_NAT16 : Int64 = -6

///|
pub const TYPE_NAT32 : Int64 = -7

///|
pub const TYPE_NAT64 : Int64 = -8

///|
pub const TYPE_INT8 : Int64 = -9

///|
pub const TYPE_INT16 : Int64 = -10

///|
pub const TYPE_INT32 : Int64 = -11

///|
pub const TYPE_INT64 : Int64 = -12

///|
pub const TYPE_FLOAT32 : Int64 = -13

///|
pub const TYPE_FLOAT64 : Int64 = -14

///|
pub const TYPE_TEXT : Int64 = -15

///|
pub const TYPE_RESERVED : Int64 = -16

///|
pub const TYPE_EMPTY : Int64 = -17

///|
pub const TYPE_OPT : Int64 = -18

///|
pub const TYPE_VEC : Int64 = -19

///|
pub const TYPE_RECORD : Int64 = -20

///|
pub const TYPE_VARIANT : Int64 = -21

///|
pub const TYPE_FUNC : Int64 = -22

///|
pub const TYPE_SERVICE : Int64 = -23

///|
pub const TYPE_PRINCIPAL : Int64 = -24
